[profile.default]
solc_version = "0.8.22"
evm_version = "paris" # prevent use of PUSH0 opcode until L2 chains run out of excuses to not support it
via_ir = true
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]

verbosity = 3

remappings = [
    "forge-std/=lib/forge-std/src/",
    "wormhole-solidity-sdk/=lib/wormhole-solidity-sdk/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]